name: library

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libegl-dev
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - run: |
          rebar3 compile
          rebar3 shell --eval "egl:get_display(default_display), erlang:halt()"


  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - id: angle
        uses: erlangsters/setup-angle@v1
      - run: |
          export ANGLE_INCLUDE_DIR="${{ steps.angle.outputs.angle-location }}/include"
          export ANGLE_LIB_DIR="${{ steps.angle.outputs.angle-location }}/lib"
          rebar3 compile
          rebar3 shell --eval "egl:get_display(default_display), erlang:halt()"

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - id: angle
        uses: erlangsters/setup-angle@v1
      - run: |
          $location = "${{ steps.angle.outputs.angle-location }}"
          $env:ANGLE_INCLUDE_DIR = "$location\include"
          $env:ANGLE_LIB_DIR = "$location\lib"
          rebar3 compile
        shell: pwsh
