name: library

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libegl-dev
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - run: rebar3 compile

  # macos: % XXX: Will require ANGLE
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: erlangsters/setup-erlang@v1
  #       with:
  #         erlang-version: 28
  #         install-rebar3: true
  #     - run: rebar3 compile
